-- https://school.programmers.co.kr/learn/courses/30/lessons/131533

SELECT A.PRODUCT_CODE AS PRODUCT_CODE, SUM(B.SALES_AMOUNT) * PRICE AS SALES
FROM PRODUCT A
LEFT OUTER JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE