-- https://school.programmers.co.kr/learn/courses/30/lessons/59045

SELECT A.ANIMAL_ID AS ANIMAL_ID, A.ANIMAL_TYPE AS ANIMAL_TYPE, A.NAME AS NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_INTAKE != 'Spayed Female' AND B.SEX_UPON_OUTCOME = 'Spayed Female')
    OR (A.SEX_UPON_INTAKE != 'Neutered Male' AND B.SEX_UPON_OUTCOME = 'Neutered Male')