-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

SELECT 
    B.AUTHOR_ID AS AUTHOR_ID, 
    B.AUTHOR_NAME AS AUTHOR_NAME, 
    A.CATEGORY AS CATEGORY, 
    SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A
INNER JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES C
    ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC