-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

SELECT A.FLAVOR
FROM FIRST_HALF A
LEFT OUTER JOIN JULY B
ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3