-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT 
    DISTINCT A.CAR_ID AS CAR_ID,
    A.CAR_TYPE AS CAR_TYPE,
    ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) AS FEE
    
FROM CAR_RENTAL_COMPANY_CAR A

JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') B
ON A.CAR_TYPE = B.CAR_TYPE

JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C
ON A.CAR_ID = C.CAR_ID

WHERE A.CAR_TYPE IN ('SUV', '세단')
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
    )
    AND ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) >= 500000 
    AND ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC