-- https://school.programmers.co.kr/learn/courses/30/lessons/59411

SELECT A.ANIMAL_ID AS ANIMAL_ID, A.NAME AS NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC
LIMIT 2