-- https://school.programmers.co.kr/learn/courses/30/lessons/164670

SELECT 
    B.USER_ID AS USER_ID, 
    B.NICKNAME AS NICKNAME, 
    CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID
HAVING COUNT(A.WRITER_ID) >= 3
ORDER BY USER_ID DESC